# https://probot.github.io/apps/boring-cyborg/
---
labelPRBasedOnFilePath:
  tests:
    - src/tests/**/*
  src:
    - src/*
  docs:
    - docs/**/*

firstIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!
