# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    assignees:
      - "TomerFi"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    assignees:
      - "TomerFi"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    assignees:
      - "TomerFi"
    labels:
      - "type: dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
