---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
    groups:
      gh-actions:
        patterns:
          - "*"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
      include: "scope"
    versioning-strategy: increase-if-necessary
    groups:
      dev-deps:
        dependency-type: "development"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
