# https://github.com/marketplace/actions/labeler
---
"scope: project":
  - ./*
"scope: tests":
  - src/tests/**/*
"scope: sources":
  - src/**/*
"scope: docs":
  - docs/**/*
"scope: ci":
  - .github/**/*
