---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch
        args: ["--branch", "dev"]
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 7c55798a78262d14b2074abf623d8a992ebb70d4  # frozen: v0.16.2
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/astral-sh/ty-pre-commit
    rev: a4405bd34b6505ed51226ba2a5b5428625177d6a  # frozen: v0.0.69
    hooks:
      - id: ty
        args: [--isolated]

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca  # frozen: v1.7.12
    hooks:
      - id: actionlint

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3aa28ce11a84d747c5695ad10b81945f2400b54f  # frozen: v3.8.0
    hooks:
      - id: editorconfig-checker

  # - repo: https://github.com/TomerFi/aicfg
  #   rev: 2e26b58b953cb06b64837d5769edde559ba4d91f  # frozen: v0.0.6
  #   hooks:
  #     - id: link
  #       args: ["agents", "--to", "claude-code"]

  - repo: https://github.com/hadolint/hadolint
    rev: 2eece55955ced00200be9729e9728cb7dacca505  # frozen: v2.15.1
    hooks:
      - id: hadolint

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 8d582f54b8e4cc5a61a85eeed1f54bbdb1e294fc  # frozen: 0.12.3
    hooks:
      - id: uv-lock
