---
name: Pages Deploy

on:
  release:
    types: [published]

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    environment: github-pages
    if: ${{ github.ref != 'refs/tags/early-access' }}
    name: Build documentation site and deploy to GH-Pages
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.ref }}

      - name: Setup Python 3.9
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9

      - name: Cache pip repository
        uses: actions/cache@v2.1.7
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements_docs.txt') }}

      - name: Prepare python environment
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements_docs.txt

      - name: Build documenation site
        run: |
          sphinx-build -b spelling docs docsbuild
          sphinx-build -b linkcheck docs docsbuild
          sphinx-build -b singlehtml docs docsbuild

      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docsbuild
          cname: switcher-webapi.tomfi.info
          commit_message: 'docs: deployed documentation site'
