---
name: Pages Deploy

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  UV_PYTHON: "3.13"

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write
    if: ${{ github.ref != 'refs/tags/early-access' }}
    name: Build documentation site and deploy to GH-Pages
    steps:
      - name: Source checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --no-install-project --group docs

      - name: Build documentation site
        run: uv run --locked mkdocs build

      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          cname: switcher-webapi.figenblat.com
          commit_message: 'docs: deployed to gh-pages for ${{ github.ref }}'
