---
name: Pages Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - switcher-webapi-released

env:
  MAIN_PY_VER: 3.9

jobs:
  deploy-pages:
    if: github.actor == 'TomerFi'
    runs-on: ubuntu-latest
    name: Build documentation site and deploy to GH-Pages
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.MAIN_PY_VER }}

      - name: Cache pip repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements_docs.txt') }}-${{ env.MAIN_PY_VER }}

      - name: Prepare python environment
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements_docs.txt

      - name: Build documenation site
        run: |
          sphinx-build -b spelling docs docsbuild
          sphinx-build -b linkcheck docs docsbuild
          sphinx-build -b singlehtml docs docsbuild

      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docsbuild
          cname: switcher-webapi.tomfi.info
          commit_message: 'docs: deployed documentation site '
