---
name: Pull request build

on:
  pull_request_target:
    branches:
      - dev

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    name: Lint documentation files
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Lint markdown files
        uses: prologic/action-markdownlint@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error

      - name: Check for spelling mistakes
        uses: reviewdog/action-misspell@v1.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          reporter: github-pr-check
          level: error

  build-app:
    runs-on: ubuntu-latest
    needs: [lint-docs]
    name: Build project
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Setup Python 3.9
        uses: actions/setup-python@v2.3.0
        with:
          python-version: 3.9

      - name: Cache pip repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements_test.txt') }}

      - name: Prepare python environment
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements_test.txt

      - name: Install deno runtime
        uses: denoland/setup-deno@v1.1.0

      - name: Check license headers on source files
        run: deno run --unstable --allow-read https://deno.land/x/license_checker@v3.1.3/main.ts

      - name: Lint project with python linters
        run: |
          bandit -r -x app/tests/* app/ docs/
          black --check app/ docs/
          flake8 --count --statistics app/ docs/
          isort --check-only app/ docs/
          mypy --ignore-missing-imports app/ docs/
          doc8 docs/
          yamllint --format colored --strict .

      - name: Test project
        run: pytest -v --cov --cov-report=xml:coverage.xml --junit-xml junit.xml

      - name: Push coverage and test reports as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: reports
          if-no-files-found: error
          path: |
            ./coverage.xml
            ./junit.xml

  build-docker:
    runs-on: ubuntu-latest
    needs: [lint-docs]
    name: Build docker
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.4.0

      - name: Lint Dockerfile
        uses: luke142367/Docker-Lint-Action@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: getDate
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build docker image (no push)
        uses: docker/build-push-action@v2.7.0
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.getDate.outputs.date }}
            VERSION=testing
          tags: tomerfi/switcher_webapi:testing
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true

      - name: Delete docker image
        run: docker image rm tomerfi/switcher_webapi:testing

  report:
    runs-on: ubuntu-latest
    name: Push coverage report to CodeCov
    needs: [build-app, build-docker]
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0

      - name: Download coverage report from artifacts
        uses: actions/download-artifact@v2
        with:
          name: reports
          path: reports

      - name: Report test summary
        uses: EnricoMi/publish-unit-test-result-action@v1.23
        if: always()
        with:
          test_changes_limit: 0
          files: reports/junit.xml

      - name: Push to CodeCov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: reports/coverage.xml
          fail_ci_if_error: true
