---
name: Pull request docker

on:
  pull_request:
    branch: dev

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify docker image
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Lint Dockerfile
        uses: reviewdog/action-hadolint@v1.19
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error

      - name: Get current date
        id: getDate
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
        with:
          driver-opts: image=moby/buildkit:buildx-stable-1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-

      - name: Build docker image (no push)
        uses: docker/build-push-action@v2.5.0
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.getDate.outputs.date }}
            VERSION=testing
          tags: tomerfi/switcher_webapi:testing
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true

      - name: Test container structure
        uses: brpaz/structure-tests-action@v1.1.2
        with:
          image: tomerfi/switcher_webapi:testing
          configFile: container_structure.yml

      - name: Delete docker image
        run: docker image rm tomerfi/switcher_webapi:testing
